### ISSUE TITLE
Strategy for having the vx.y.z tag displayed by GitHub

### ISSUE THREAD

**Issue by mxcl** [sersoft-gmbh/running-release-tags-action#22]
Great action, thanks.

On my repos it always shows the `v1` release as “most recent”:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/58962/123167483-95bd2e00-d444-11eb-8f26-3dcea577e199.png">

(https://github.com/mxcl/xcodebuild/releases/tag/v1)

I think this makes it look like my repos are not getting updated. For example, I released *today* but the latest release is “18 days ago”.

I was wondering if you can think of a solution?

I am aware that this happens because I am triggering your action after creating the `vx.y.z` release tag. So the `v1` tag naturally is “newer”. Thanks.

**Comment by ffried** [comment]
That's a very good question! I've noticed this myself and especially with Dependabot it leads to weird behavior.

One idea I've had was to check whether editing a release would mark it as "most recent". You wouldn't have tried this by any chance?
If that works, I could simply edit the triggering release _after_ updating the others. Although GitHub probably checks for actual edits and simply posting the same release won't suffice. 🤔

**Comment by mxcl** [comment]
I just tried editing the latest `vx.y.x` release and indeed, that caused GitHub to label it the latest release on the project home:

https://github.com/mxcl/xcodebuild

**Comment by ffried** [comment]
Did you actually change something or simply saved it w/o making any changes?

**Comment by mxcl** [comment]
I edited the description from blank to something about the release. Not sure if the API requires a change or not, but did the change to make sure.

**Comment by ffried** [comment]
Ok, thanks! I'll play around with it some more. If an "empty save" enough, that would be rather simple. Otherwise I need to e.g. append a space to the title and remove it again. Or maybe find some other attribute of the release I can safely change.

**Comment by ffried** [comment]
Quick update: simply editing and saving a release w/o making any changes doesn't mark it as "latest release".
Which means I really need to change something on the release (and probably reverse it).

**Comment by ffried** [comment]
I've just published v1.2.0 which adds a new input `update-full-version`.
It will append a `&nbsp;` to the body of the release associated with the tag its run for (either passed in via the `tag` input or read from the environment). Once appended, it will restore the old release body again.

Note that depending on what token you're using to run this action, this will trigger an edit on the release - meaning it has the possibility for endless loops if the action is triggered for edited releases as well.
I'm still thinking of a way around that, but it would involve a bit more in-depth analysis on what was actually changed.

**Comment by mxcl** [comment]
Fab thanks! I imagine most use the `GITHUB_TOKEN` so it cannot trigger a cycle. But certainly something to document for this `input`.

**Comment by ffried** [comment]
Great idea! I'll add a note to the README later...

Funny thing is, that Dependabot seems to choose another measure of "what's newer", since it still uses `v1.2` over `v1.2.0`: https://github.com/sersoft-gmbh/swifty-docs-action/pull/30
🤷

**Comment by ffried** [comment]
Quick update on this: v3.0.0 sends a new `"make_latest": "false"` parameter when creating releases (GitHub added support for this in the API). This should prevent the need for 'touching' the full release.

According to [this run](https://github.com/sersoft-gmbh/running-release-tags-action/actions/runs/6214249432/job/16866008082#step:3:79), it seems to work.

I've left the input for now, though. But it will now check whether an update is actually needed, before doing so. A corresponding log message is also printed if no update was needed.
